version: '3'

services:
    app:
        container_name: app
        build:
          context: app
        restart: always
        ports:
            - '5000:5000'
        volumes:
            - ./app:/app
            - ./data:/data
        environment:
            - FLASK_DEBUG=1
        networks:
            - backend
        links:
          - db
        depends_on:
          - db
    db:
        platform: linux/x86_64
        container_name: db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: education_uiuc_pwd
            MYSQL_DATABASE: education_uiuc
        ports:
            - '3308:3306'
        # volumes:
        #     - ./database:/var/lib/mysql
        networks:
            - backend
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: always
      ports:
        - 8081:80
      networks:
          - backend
      depends_on:
        - db
    db_init:
      build:
        context: app
      depends_on:
        - db
      links:
        - db
      networks:
          - backend
      command: python /app/init.py
      volumes:
          - ./app:/app
          - ./data:/data
networks:
    backend:
